name: yurttaye_mobile
description: A Flutter app to view YurttaYe menus
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png